name: item_master
profile: snowflake
version: '5.2.0'
config-version: 2

snapshot-paths:
  - snapshots
analysis-paths:
  - analysis
clean-targets:
  - target
data-paths:
  - data
macro-paths:
  - macros
source-paths:
  - models
test-paths:
  - tests
target-path: target

vars:
  load_date: '2022-02-21'
  tpch_size: 10 #1, 10, 100, 1000, 10000

models:
  item_master:
    raw_stage:
      tags:
        - 'raw'
      materialized: table
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: table
    vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'sat'
